# -*- coding: utf-8 -*-

'''
Problem45 「Triangular, pentagonal, and hexagonal」

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	T(n)=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	P(n)=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	H(n)=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T(285) = P(165) = H(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
(T(285) = P(165) = H(143) = 40755の次に三角数でも五角数でも六角数でもある数を求めよ。)
'''

import time

def find_next_triangle_pentagonal_hexagonal(n=144):
    while True:
        h = n * (2*n - 1)
        if ((-1 + (1 + 8*h) ** 0.5)/2).is_integer() and (((1 + 24 * (h)) ** 0.5 + 1) / 6).is_integer():
            return h
        else:
            n += 1

if __name__ == '__main__':
    start = time.time()

    print(find_next_triangle_pentagonal_hexagonal())    # answer 1533776805

    elapsed_time = time.time() - start
    print("elapsed_time:{}".format(round(elapsed_time, 5)) + "[sec]")   # 0.01827sec
